name: Upstream utils

on:
  pull_request:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all history and metadata
        run: |
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Configure committer identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Run update_drake.py
        run: |
          cd upstream_utils
          ./update_drake.py
      - name: Run update_eigen.py
        run: |
          cd upstream_utils
          ./update_eigen.py
      - name: Run update_fmt.py
        run: |
          cd upstream_utils
          ./update_fmt.py
      - name: Run update_libuv.py
        run: |
          cd upstream_utils
          ./update_libuv.py
      - name: Run update_llvm.py
        run: |
          cd upstream_utils
          ./update_llvm.py
      - name: Run update_mpack.py
        run: |
          cd upstream_utils
          ./update_mpack.py
      - name: Run update_stack_walker.py
        run: |
          cd upstream_utils
          ./update_stack_walker.py
      - name: Run update_memory.py
        run: |
          cd upstream_utils
          ./update_memory.py
      - name: Add untracked files to index so they count as changes
        run: git add -A
      - name: Check output
        run: git --no-pager diff --exit-code HEAD
